// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArQlajOP2FCEiKlk5YW1Fv-49Sbizb-90',
    appId: '1:353826152405:web:cd365051dbd332ac5e275c',
    messagingSenderId: '353826152405',
    projectId: 'business-manager-a3ec7',
    authDomain: 'business-manager-a3ec7.firebaseapp.com',
    storageBucket: 'business-manager-a3ec7.appspot.com',
    measurementId: 'G-9Z02E5EQEE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3VeHOMy7W2Lp4-zNDlfOm091jmcyG-90',
    appId: '1:353826152405:android:892a9cb1f7555df25e275c',
    messagingSenderId: '353826152405',
    projectId: 'business-manager-a3ec7',
    storageBucket: 'business-manager-a3ec7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJCGyQFqvNS-0PdRAqcWS9r3Ofkv9gq4k',
    appId: '1:353826152405:ios:0ec734b80f5c14de5e275c',
    messagingSenderId: '353826152405',
    projectId: 'business-manager-a3ec7',
    storageBucket: 'business-manager-a3ec7.appspot.com',
    iosClientId: '353826152405-39su19shl1p229gtrt70kle1tmqoctil.apps.googleusercontent.com',
    iosBundleId: 'com.example.businessManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJCGyQFqvNS-0PdRAqcWS9r3Ofkv9gq4k',
    appId: '1:353826152405:ios:0ec734b80f5c14de5e275c',
    messagingSenderId: '353826152405',
    projectId: 'business-manager-a3ec7',
    storageBucket: 'business-manager-a3ec7.appspot.com',
    iosClientId: '353826152405-39su19shl1p229gtrt70kle1tmqoctil.apps.googleusercontent.com',
    iosBundleId: 'com.example.businessManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArQlajOP2FCEiKlk5YW1Fv-49Sbizb-90',
    appId: '1:353826152405:web:1a0dea887cda93b15e275c',
    messagingSenderId: '353826152405',
    projectId: 'business-manager-a3ec7',
    authDomain: 'business-manager-a3ec7.firebaseapp.com',
    storageBucket: 'business-manager-a3ec7.appspot.com',
    measurementId: 'G-N4C2NLPT8Y',
  );

}